name: sideBias
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - tifffile
  - jupyter
  - ipykernel
  - scikit-learn
  - pip 