batch_size: 500       # lower batch size if you run into GPU memory issues
fast_disk: "C:/suite2p_fast"
delete_bin: false
move_bin: true
nplanes: 1
nchannels: 1
functional_chan: 1
tau: 1.26               # ops.py = 1.25
fs: 15.0
save_mat: false         
combined: true
save_NWB: 0.0
aspect: 1.0
do_bidiphase: false
bidiphase: 0
bidi_corrected: true
num_workers: 0
num_workers_roi: 0
do_registration: true     
two_step_registration: 0.0
keep_movie_raw: false
nonrigid: true
useGPU: true
two_step_registration: true
nimg_init: 1000        # ops.py = 500
maxregshift: 0.1
align_by_chan: 1
reg_tif: false           # ops.py = false
subpixel: 10
smooth_sigma_time: 0.0
smooth_sigma: 1.15
th_badframes: 1.0
norm_frames: true
force_refImg: false
pad_fft: false
connected: true
navg_frames_svd: 5000     #nsvd_for_roi: 1000
max_iterations: 20      # ops.py = 30
ratio_neuropil: 6.0
ratio_neuropil_to_cell: 3.0
tile_factor: 1.0
threshold_scaling: 0    # ops.py = 0
allow_overlap: true
max_overlap: 0.75       # ops.py = 0.75
inner_neuropil_radius: 2
outer_neuropil_radius: "inf"
min_neuropil_pixels: 350
baseline: maximin       # not listed in ops.py
win_baseline: 60.0
sig_baseline: 10.0
prctile_baseline: 8.0
diameter: 20            # ops.py = [14]
neucoeff: 0.7
anatomical_only: 3
pretrained_model: cyto
cellprob_threshold: -6.0
flow_threshold: 0.0
roidetect: true
spikedetect: true
sparse_mode: true
spatial_scale: 0
high_pass: 100.0
spatial_hp_detect: 25.0
preclassify: 0.0
denoise: 0.0
soma_crop: 1.0
neuropil_extract: true
use_builtin_classifier: false
classifier_path: ""
spatial_hp_cp: 0.0